### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by cutleraging** [dgrun/RaceID3_StemID2_package#10]
Thanks for a nice package to calculate transcriptional noise. I have a couple questions...

1. Why is there a noise value for each gene in each cell? From my understanding, noise (or variance) is representative of a collection of data points. So it is confusing to me how each gene in each cell has their own noise value. I would expect there to be a noise value per cluster. Please help me understand this.

2. I am working with a 10X genomics dataset. I have converted my pre-clustered seurat object, run the prunKNN function, and the compTBNoise function. I used gamma = 0.01 (higher values of gamma gave ever higher spearman correlations). From the UMI vs noise plot, you can see that there appear to be 2 populations of cells with different total UMIs. 

![image](https://github.com/dgrun/RaceID3_StemID2_package/assets/84161843/6a54e21c-989d-405d-98a4-ff557f41e56e)

When looking at some of the plots for the top noisy genes, I see that there does seem to be a dependence of noise on the mean. A negative correlation.
![image](https://github.com/dgrun/RaceID3_StemID2_package/assets/84161843/c41414e6-b9e0-4612-a9c1-74e68cfa6921)

What should I do about this? Is it an issue with how the cells were clustered? Or do I have to process the cells with high total UMI and low total UMI separately?

3. It seems like if I want to compare different groups, that they should both be loaded and clustered in the same object. However, when using standard clustering, cells from my 2 conditions are within the same clusters. What is the recommended way to compare two conditions? Should they be processed together or separately?

4. I notice that for some functions, such as diffNoisyGenesTB, requires that the graphCluster function be run. But if I have started with a seurat object where I have already done the clustering, how do I now use these functions?

Thanks a lot!
Ronnie

**Comment by dgrun** [comment]
Dear Ronnie,

thanks for your questions.

Here are some quick answers:

Reg. 1: The noise is computed for the pruned neighbourhood of each individual cell. It could be averaged across all cells (i.e., neighbourhoods) of a cluster, but this would discard local information.

Reg. 2: It is important that you run the pruneKnn function on the raw (i.e., normalised) counts. Otherwise, the results will be non-sensical. You could then still run the graphCluster function, and overwrite the partition slot with the Seurat clustering partition. If you see a noise dependence on the total UMI counts for particular genes, this could well be biological. Imagine you encounter two cell states with different total RNA count, and in one of these states Malat1 exhibits high biological variability. If you see this on average across all genes, it is more likely to be technical, and you have to adjust the prior. However, in your case it does not look like this.

Reg. 3: When dealing with different conditions, I strongly advice to analyse separately and not integrate. This would mix neighbourhood, and the noise you are observing could just be noise across conditions (biological and/or technical). 

Reg. 4: Just run graphCluster and overwrite the partition component with your desired clustering partition. Please note that clusters in VarID start counting at 1. When overwriting with Seurat clusters, just add 1.

Please let me know if you have any further questions.

Dominic

**Comment by cutleraging** [comment]
Hi Dominic,

Thanks for your response!

Reg. 1: Okay that makes a bit more sense. When noise is calculated for each neighborhood, are the boundaries of the neighborhood determined by the clustering? For example, if I have cells in different states of the cell cycle and the clustering is done to reflect this, I would not want the neighborhoods to contain cells from different clusters of cells with different cell cycle states.

Reg. 2: I am a bit confused what you mean by raw counts. Usually this refers to the UMI counts that are provided by cellRanger and are not yet normalized. This is also what the function documentation seems to imply (values corresponding to UMI counts). But you mentioned normalized. So, wondering which it is? Which do you give as input to pruneKNN and which do you give as input to compTBNoise?

Thanks,
Ronnie

**Comment by dgrun** [comment]
Hi Ronnie,

Reg. 1: We start with k-nearest neighbourhoods. k is a free parameter (knn) of pruneKnn with default knn=25. These neighbourhoods are pruned to remove outliers. The choice of knn depends on how densely cell states are sampled in your dataset. For large datasets you can try higher knn. Clusters are not at all informative for these neighbourhoods.

Reg. 2: Sorry, that was a typo. I meant to write "non-normalized".  So you applied it correctly.

Dominic
